language: python
sudo: false
addons:
  apt:
    packages:
      - python-subversion
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/venv-lib"
matrix:
  include:
    - os: linux
      python: "2.7_with_system_site_packages"
      env: tracdb= build=minimum
    - os: linux
      python: "2.7_with_system_site_packages"
      env: tracdb=
    - os: linux
      python: "2.7_with_system_site_packages"
      env: tracdb=sqlite
    - os: linux
      python: "2.7_with_system_site_packages"
      env: tracdb=postgres
    - os: linux
      python: "2.7_with_system_site_packages"
      env: tracdb=mysql
    - os: osx
      language: generic
      env: pyver=2.7 tracdb= build=minimum
    - os: osx
      language: generic
      env: pyver=2.7 tracdb=
    - os: osx
      language: generic
      env: pyver=2.7 tracdb=sqlite
    - os: osx
      language: generic
      env: pyver=2.7 tracdb=postgres
before_install:
  - rvm get head
  - |
    set -e
    case "$tracdb" in
      postgres)
        if [ "$TRAVIS_OS_NAME" = osx ]; then
          rm -rf /usr/local/var/postgres
          pg_ctl initdb --pgdata /usr/local/var/postgres
          pg_ctl -w start --pgdata /usr/local/var/postgres --log /usr/local/var/postgres/postgresql.log || {
            rc=$?
            cat /usr/local/var/postgres/postgresql.log
            exit $rc
          }
          createuser -s postgres
        fi
        tracdb_version="PostgreSQL: $(psql -U postgres -t -c 'SELECT version()')"
        echo "$tracdb_version"
        psql -U postgres -e -c "CREATE USER tracuser NOSUPERUSER NOCREATEDB CREATEROLE PASSWORD 'password';"
        psql -U postgres -e -c "CREATE DATABASE trac OWNER tracuser;"
        ;;
      mysql)
        tracdb_version="MySQL: $(mysql -u root -sN -e 'SELECT version()')"
        echo "$tracdb_version"
        mysql -u root -v -e "CREATE DATABASE trac DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"
        mysql -u root -v -e "CREATE USER tracuser@localhost IDENTIFIED BY 'password';"
        mysql -u root -v -e "GRANT ALL ON trac.* TO tracuser@localhost; FLUSH PRIVILEGES;"
        ;;
      *)
        tracdb_version=
        ;;
    esac
  - |
    set -e
    if [ "$TRAVIS_OS_NAME" = osx ]; then
      test -d $HOME/venv-lib || mkdir $HOME/venv-lib
      PYTHONPATH=$HOME/venv-lib /usr/bin/easy_install-$pyver -ZU -d $HOME/venv-lib virtualenv
      PYTHONPATH=$HOME/venv-lib /usr/bin/python$pyver -m virtualenv $HOME/venv-$pyver
      source $HOME/venv-$pyver/bin/activate
      python --version
      pip --version
    fi
install:
  - test -d "$HOME/.pip" || mkdir "$HOME/.pip"
  - ( echo "[global]"; echo "cache-dir = $HOME/.cache/pip" ) >"$HOME/.pip/pip.conf"
  - |
    pip install --upgrade pip
    requires='Jinja2 lxml twill==0.9.1'
    if [ "$build" != minimum ]; then requires="$requires Genshi==0.7 Babel!=2.3.0,!=2.3.1 Pygments docutils textile pytz"; fi
    if [ "$tracdb" = postgres ]; then requires="$requires psycopg2"; fi
    if [ "$tracdb" = mysql ]; then requires="$requires MySQL-python"; fi
    pip install $requires
  - pip freeze
  - |
    set -e
    case "$tracdb" in
      sqlite)   tracdb_uri='sqlite:test.db' ;;
      postgres) tracdb_uri='postgres://tracuser:password@localhost/trac?schema=tractest' ;;
      mysql)    tracdb_uri='mysql://tracuser:password@localhost/trac' ;;
      *)        tracdb_uri= ;;
    esac
    echo ".uri = $tracdb_uri" >Makefile.cfg
script:
  - echo "$tracdb_version"
  - |
    targets=Trac.egg-info
    if [ "$build" != minimum ]; then targets="$targets compile"; fi
    targets="$targets unit-test functional-test"
    make $targets
notifications:
  email:
    recipients:
      - trac-builds@googlegroups.com
